### ISSUE TITLE
Add support for user-defined headers for `webhook` destinations

### ISSUE THREAD

**Issue by rsioss** [Stedi-Demos/bootstrap#22]
We currently support basic webhook destinations (unauthenticated). It should be expected that customers will want to include support for some form of authentication to their internal API webhook destinations. Adding support for user-defined headers seems like a fairly straightforward initial solution for this.

**Comment by rsioss** [comment]
in addition to user-defined headers, we should also add support for customizing the HTTP verb used

**Comment by russellpekala** [comment]
Would be great to have ability to rotate header via STEDI API if possible too. 

Great work on all the webhook stuff!

**Comment by rsioss** [comment]
Thank you, @russellpekala! It should already be possible to rotate the header via the Stash [GetValue](https://www.stedi.com/docs/api/stash#GetValue) and [SetValue](https://www.stedi.com/docs/api/stash#SetValue) APIs. You could download the current config via `GetValue`, update the header values in the downloaded config as needed, and then use `SetValue` to perform the update.

That said, I added a comment on https://github.com/Stedi-Demos/bootstrap/issues/26 that it would be great to include support for downloading / updating the existing config
