### ISSUE TITLE
Format Outbound EDI Files with New Lines

### ISSUE THREAD

**Issue by russellpekala** [Stedi-Demos/bootstrap#42]
Hey! I am super enjoying getting up to speed with Stedi. I have followed the tutorials here. I am wondering whether there is a way to have Stedi functions format outbound EDI files with new lines in them so that they look a little more readable than what I have below (the output of the EDI outbound translation from the bootstrap). 

<img width="814" alt="image" src="https://user-images.githubusercontent.com/23023662/216907506-dae68ba0-ed84-4330-8dea-55f7208233cf.png">

**Comment by rsioss** [comment]
hey @russellpekala! we're thrilled to hear that you are having fun getting ramped up with Stedi. as for your question regarding the generated X12 output, this is actually possible via configuration on the corresponding guide. You can select either newline (`\n`) or carriage return (`\r`) as your segment delimiter in the Overview section of the guide:  

![image](https://user-images.githubusercontent.com/39536918/217999241-1334e41a-9abc-44a6-af88-f97161eb8249.png) 

Keep us posted with your progress, and don't hesitate to reach out if you have any additional questions! I'm going to close this issue, but if this answer doesn't address your concern fully please don't hesitate to reopen it. (cc: @dkanter14, just FYI)
