### ISSUE TITLE
Support dynamically choosing a guideId based on the GS-08 

### ISSUE THREAD

**Issue by dkanter14** [Stedi-Demos/bootstrap#58]
For X12 HIPAA Guides, there are multiple "types" of transaction sets. For example, the 837 has a "professional" and "institutional" 837. These are indicated in the GS-08: 

GS-08 for professional = "005010X222"
GS-08 for institutional = "005010X223"

The bootstrap repo cannot dynamically choose which guide to use based on the full release with industry extensions.

- [ ] Allow customer to add the release (with extension) in partnership config in Stash when they want to select a guide for a specific release

CC @RossWilliams

**Comment by russellpekala** [comment]
This is amazing, thank you <3
