### ISSUE TITLE
Sort Logs in Stedi Functions by Most Recent

### ISSUE THREAD

**Issue by russellpekala** [Stedi-Demos/bootstrap#68]
I find myself debugging functions using the Stedi Functions Log (https://www.stedi.com/app/functions/logs?account=example-account#function=edi-inbound,tab=logs)

I wish I didn't have to scroll to the bottom to see recent logs, I wish they were sorted the other way so that recent logs are on top. 

I know this isn't really an issue with the Bootstrap repo, but wanted to file it here since it is part of the experience using the Bootstrap flow.

**Comment by dkanter14** [comment]
Hey @russellpekala - we have this logged for our functions / logs team to tackle in the UI. Going to close it from Bootstrap project, but we are tracking internally.
