### ISSUE TITLE
Generated acks always return with the `P` UsageIndicatorCode

### ISSUE THREAD

**Issue by git-smp** [Stedi-Demos/bootstrap#95]
https://github.com/Stedi-Demos/bootstrap/blob/80cbecb1adfa5de6c08c6515e46ae124cbe63a65/src/lib/acks.ts#L51

Currently all acks return with the usage indicator code set to `P`, even if the usage indicator is set to `T` or `I`. The X12 ack library should have a way of indicating what usage indicator code it should generate the 997 with.

**Comment by git-smp** [comment]
I've also noticed that the response will not include the correct ISA-11 field. 

Input ISA
```
ISA*00*          *00*          *14*000000002TEST  *12*0000000001     *230321*1144*U*00401*000000043*0*T*;~
```

Output 997
```
ISA*00*          *00*          *12*0000000001     *14*000000002TEST  *230322*2008*^*00401*000000015*0*T*
```

For some reason when calling the `x12.ack()` it responds with a `^` for ISA-11 instead of a `U`

**Comment by RossWilliams** [comment]
Thank you for reporting this issue. This is being worked on.
