### ISSUE TITLE
[Engine] Destroy script doesn't seem to clean up functions or buckets

### ISSUE THREAD

**Issue by ZackKanter** [Stedi-Demos/bootstrap#98]
<img width="1557" alt="Screenshot 2023-03-25 at 2 19 05 PM" src="https://user-images.githubusercontent.com/2780696/227734720-e4ccc2b6-17af-4f58-904b-1ab4da7472d1.png">
<img width="1557" alt="Screenshot 2023-03-25 at 2 19 11 PM" src="https://user-images.githubusercontent.com/2780696/227734712-881d8e58-b767-464b-9cb9-806aa7436f29.png">
<img width="1268" alt="Screenshot 2023-03-25 at 2 20 05 PM" src="https://user-images.githubusercontent.com/2780696/227734714-f05699fd-54d9-46f7-a862-74db20cd0a61.png">

**Comment by RossWilliams** [comment]
deleting buckets used by an Engine is blocked until the Engine itself can be deleted.

**Comment by ZackKanter** [comment]
Sorry for not being more specific – I wouldn't expect running Bootstrap destroy to delete Engine's buckets. I meant that running Bootstrap destroy doesn't seem to delete the buckets created by Bootstrap itself (unless I'm misunderstanding what Bootstrap creates).

Example:

<img width="746" alt="Screenshot 2023-03-27 at 9 45 46 AM" src="https://user-images.githubusercontent.com/2780696/227957158-2c4a6ae8-6f31-4161-b98c-71040c91c2e1.png">

<img width="1184" alt="Screenshot 2023-03-27 at 9 45 59 AM" src="https://user-images.githubusercontent.com/2780696/227957225-05d5623b-b838-4606-85b0-c967af1ff626.png">

**Comment by BDQ** [comment]
Closing, this was a stale NPM issue.

**Comment by ZackKanter** [comment]
> Closing, this was a stale NPM issue.

Some additional color: this was my fault – I pulled the latest changes but didn't run `npm ci` again. Sorry for the churn.

After running the destroy script:

- All functions were deleted successfully
- The buckets (the SFTP v1 and `{accountId}-executions` buckets were not deleted, which is the intended behavior. We should document in the destroy readme that the destroy script doesn't clean up these buckets.
